hyperskill_project:
  id: 126
  ide_files: https://cogniterra.org/media/attachments/lesson/25102/additional_files.json
  is_template_based: true
  use_ide: true
update_date: "Thu, 10 Oct 2024 13:30:58 UTC"
stages:
  - id: 668
    step: 10770
    is_completed: true
  - id: 669
    step: 10771
    is_completed: true
  - id: 670
    step: 10772
    is_completed: true
  - id: 671
    step: 10773
    is_completed: true
  - id: 672
    step: 10774
    is_completed: true
topics:
  0:
    - title: Introduction to Kotlin
      theory_id: 4350
    - title: "Basic literals: numbers, strings and characters"
      theory_id: 4351
    - title: Writing first program
      theory_id: 4362
    - title: Standard output
      theory_id: 4425
  1:
    - title: Values and variables
      theory_id: 4371
    - title: Constants and val variables
      theory_id: 17408
    - title: Data types
      theory_id: 4388
    - title: Comments
      theory_id: 4406
    - title: Kotlin style guide. Coding conventions
      theory_id: 4419
    - title: Naming variables
      theory_id: 4389
    - title: Invoking functions
      theory_id: 4575
    - title: Standard input with Java Scanner
      theory_id: 4445
  2:
    - title: String basics
      theory_id: 12553
    - title: String templates
      theory_id: 4547
    - title: Boolean type and operations. True and false
      theory_id: 4515
    - title: Arithmetic operations
      theory_id: 4472
    - title: Increment and decrement
      theory_id: 10776
    - title: Properties of basic types
      theory_id: 4455
    - title: Type conversion
      theory_id: 4672
    - title: Reading data with readln
      theory_id: 11224
    - title: "When different types meet: type coercion"
      theory_id: 9506
    - title: Integers in action
      theory_id: 4488
    - title: Comparing numbers. Relational operators
      theory_id: 4525
    - title: Unicode
      theory_id: 7899
    - title: Characters. Char type
      theory_id: 4680
    - title: Working with strings
      theory_id: 12561
  3:
    - title: If expression
      theory_id: 4625
    - title: "Loops: repeat statement"
      theory_id: 4643
    - title: Ranges
      theory_id: 4633
    - title: For loop and ranges
      theory_id: 4652
  4:
    - title: Declaring functions
      theory_id: 4580
    - title: While loops
      theory_id: 4659
